repos:
-   repo: local
    hooks:
    -   id: deno-fmt
        name: Deno Format
        entry: deno fmt
        language: system
        pass_filenames: false
    -   id: deno-lint
        name: Deno Lint
        entry: deno lint --fix
        language: system
        pass_filenames: false