// Экспорт компонентов пользовательских шаблонов
export * from "./split-3-1-right"
export * from "./split-custom-3-1"
export * from "./split-custom-5-3-square"
export * from "./split-custom-5-4"
export * from "./split-custom-7"
export * from "./split-horizontal"
export * from "./split-horizontal-4"
export * from "./split-vertical"
export * from "./split-vertical-3"
export * from "./split-vertical-4"
