
export const effects = [
  {
    id: "brightness",
    type: "brightness" as const,
    name: "Яркость",
    labels: {
      ru: "Яркость",
      en: "Brightness",
    },
    duration: 0,
    ffmpegCommand: "eq=brightness=0.5",
  },
  {
    id: "contrast",
    type: "contrast" as const,
    name: "Контраст",
    labels: {
      ru: "Контраст",
      en: "Contrast",
    },
    duration: 0,
    ffmpegCommand: "eq=contrast=1.5",
  },
  {
    id: "saturation",
    type: "saturation" as const,
    name: "Насыщенность",
    labels: {
      ru: "Насыщенность",
      en: "Saturation",
    },
    duration: 0,
    ffmpegCommand: "eq=saturation=2",
  },
  {
    id: "sepia",
    type: "sepia" as const,
    name: "Сепия",
    labels: {
      ru: "Сепия",
      en: "Sepia",
    },
    duration: 0,
    ffmpegCommand: "colorize=color=brown:blend=0.3",
  },
  {
    id: "grayscale",
    type: "grayscale" as const,
    name: "Черно-белый",
    labels: {
      ru: "Черно-белый",
      en: "Grayscale",
    },
    duration: 0,
    ffmpegCommand: "colorchannelmixer=.3:.4:.3:0:.3:.4:.3:0:.3:.4:.3",
  },
  {
    id: "invert",
    type: "invert" as const,
    name: "Инверсия",
    labels: {
      ru: "Инверсия",
      en: "Invert",
    },
    duration: 0,
    ffmpegCommand: "negate",
  },
  {
    id: "hue-rotate",
    type: "hue-rotate" as const,
    name: "Оттенок",
    labels: {
      ru: "Оттенок",
      en: "Hue Rotate",
    },
    duration: 0,
    ffmpegCommand: "hue=h=90",
  },
  {
    id: "vintage",
    type: "vintage" as const,
    name: "Винтаж",
    labels: {
      ru: "Винтаж",
      en: "Vintage",
    },
    duration: 0,
    ffmpegCommand: "curves=vintage",
  },
  {
    id: "duotone",
    type: "duotone" as const,
    name: "Дуотон",
    labels: {
      ru: "Дуотон",
      en: "Duotone",
    },
    duration: 0,
    ffmpegCommand: "colorbalance=rs=0.3:gs=0.3:bs=0.3:rm=0:gm=0:bm=0:rh=-0.3:gh=-0.3:bh=-0.3",
  },
  {
    id: "speed",
    type: "speed" as const,
    name: "Скорость",
    labels: {
      ru: "Скорость",
      en: "Speed",
    },
    duration: 0.5,
    ffmpegCommand: "setpts=0.5*PTS",
  },
  {
    id: "noir",
    type: "noir" as const,
    name: "Нуар",
    labels: {
      ru: "Нуар",
      en: "Noir",
    },
    duration: 0,
    ffmpegCommand: "curves=noir",
  },
  {
    id: "cyberpunk",
    type: "cyberpunk" as const,
    name: "Киберпанк",
    labels: {
      ru: "Киберпанк",
      en: "Cyberpunk",
    },
    duration: 0,
    ffmpegCommand: "colorbalance=rs=0.5:gs=-0.5:bs=0.8",
  },
  {
    id: "dreamy",
    type: "dreamy" as const,
    name: "Мечтательный",
    labels: {
      ru: "Мечтательный",
      en: "Dreamy",
    },
    duration: 0,
    ffmpegCommand: "gblur=sigma=1.5,colorbalance=rs=0.1:gs=0.1:bs=0.1",
  },
  {
    id: "infrared",
    type: "infrared" as const,
    name: "Инфракрасный",
    labels: {
      ru: "Инфракрасный",
      en: "Infrared",
    },
    duration: 0,
    ffmpegCommand: "colorbalance=rs=0.8:gs=-0.8:bs=-0.8",
  },
  {
    id: "matrix",
    type: "matrix" as const,
    name: "Матрица",
    labels: {
      ru: "Матрица",
      en: "Matrix",
    },
    duration: 0,
    ffmpegCommand: "colorbalance=rs=-0.8:gs=0.8:bs=-0.8",
  },
  {
    id: "arctic",
    type: "arctic" as const,
    name: "Арктика",
    labels: {
      ru: "Арктика",
      en: "Arctic",
    },
    duration: 0,
    ffmpegCommand: "colorbalance=rs=-0.2:gs=0.2:bs=0.4",
  },
  {
    id: "sunset",
    type: "sunset" as const,
    name: "Закат",
    labels: {
      ru: "Закат",
      en: "Sunset",
    },
    duration: 0,
    ffmpegCommand: "colorbalance=rs=0.4:gs=0.1:bs=-0.4",
  },
  {
    id: "lomo",
    type: "lomo" as const,
    name: "Ломо",
    labels: {
      ru: "Ломо",
      en: "Lomo",
    },
    duration: 0,
    ffmpegCommand: "curves=lomo",
  },
  {
    id: "twilight",
    type: "twilight" as const,
    name: "Сумерки",
    labels: {
      ru: "Сумерки",
      en: "Twilight",
    },
    duration: 0,
    ffmpegCommand: "colorbalance=rs=-0.2:gs=-0.1:bs=0.3",
  },
  {
    id: "neon",
    type: "neon" as const,
    name: "Неон",
    labels: {
      ru: "Неон",
      en: "Neon",
    },
    duration: 0,
    ffmpegCommand: "colorbalance=rs=0.5:gs=0.5:bs=0.8,curves=increase_contrast",
  },
]
